server:
  port: 8081
spring:
  application:
    name: rides-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ridesdb
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: rideGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json:
          trusted.packages: "*"
          type.mapping: RideRequest:com.example.ridesservice.dto.request.RideRequest
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: ratingDelegation:com.example.ridesservice.dto.request.DelegateRatingRequest, paymentDelegation:com.example.ridesservice.dto.request.DelegatePaymentRequest, DriverRequest:com.example.ridesservice.dto.request.DriverRequest
topic:
  name:
    driver: driver-search
    payment: payment-delegate
    rating: rating-delegate
kafka:
  partitions:
    count: 5
  replicas:
    count: 1
